from pathlib import Path
import json
p=Path(__file__).resolve().parents[1]

def asset_path(file):
    cutout=f'assets/cutouts/{file}.png'
    return cutout if (p/'composition'/cutout).exists() else f'assets/{file}.png'

def sprite(n, cls='', style=''):
    return f'<div class="object object-{n} {cls}" style="{style}" role="img" aria-label="{["두뇌","대화","연결","터미널과 파일","작업 앱","완성된 파일"][n]}"><img src="{asset_path("object-atlas")}" alt="" draggable="false"></div>'

def logo(name, label='', cls=''):
    ext='png' if name in ['claude','gemini-cli','antigravity','google-company','hermes-agent','kakaotalk'] else 'svg'
    return f'<div class="brand {cls}"><img src="assets/logos/{name}.{ext}" alt="{label or name}" draggable="false">'+(f'<span>{label}</span>' if label else '')+'</div>'

def art(file,cls,style,alt,key=''):
    motion_key=f' data-motion-key="{key}"' if key else ''
    return f'<img class="story-art {cls}" style="{style}" src="{asset_path(file)}" alt="{alt}" draggable="false"{motion_key}>'

def arrow(cls,style,left=False):
    path='M290 35H10 M35 12L10 35L35 58' if left else 'M10 35H290 M265 12L290 35L265 58'
    return f'<svg class="flow-arrow {cls}" style="{style}" viewBox="0 0 300 70" aria-hidden="true"><path d="{path}" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg>'

def cross(cls,style):
    return f'<svg class="blocked-mark {cls}" style="{style}" viewBox="0 0 100 100" aria-hidden="true"><path d="M18 18L82 82 M82 18L18 82" fill="none" stroke="#c6362e" stroke-width="10" stroke-linecap="round" pathLength="100" stroke-dasharray="100" stroke-dashoffset="0"/></svg>'

slides=[]
slides.append('<div class="story-title cover-title"><h1 data-enter><span>ChatBot에서</span><strong>Agent로</strong></h1></div>' )
slides.append('<div class="company-stack makers-stack"><div class="company-google enter-brand"><img src="assets/logos/google-company.png" alt="Google 공식 회사 로고"></div>'+logo('anthropic-company','Anthropic','enter-brand')+logo('openai-company','OpenAI','enter-brand company-openai')+'</div>'+arrow('makers-arrow','left:795px;top:505px;width:245px;height:65px;')+sprite(0,'large-object','left:1090px;top:155px;width:710px;height:710px;')+'<h2 class="makers-label" data-enter>AI 모델</h2>' )
slides.append(sprite(0,'large-object','left:120px;top:95px;width:900px;height:900px;')+f'<div class="side-copy model-names"><h2 data-enter>AI 모델</h2><div class="brand-stack">{logo("claude","Opus · Fable","enter-brand")}{logo("gemini","Flash · Pro","enter-brand")}{logo("chatgpt","GPT-6 Astra","enter-brand")}</div></div>')
slides.append('<h2 class="scene-word" data-enter>다운로드</h2>'+art('model-package','download-package','left:145px;top:285px;width:670px;height:670px;','다운로드 가능한 모델 패키지')+arrow('download-arrow','left:875px;top:525px;width:230px;height:70px;')+art('local-llm','download-computer','left:1180px;top:305px;width:605px;height:605px;','모델을 받아 실행하는 컴퓨터')+'<span class="download-examples" data-enter>Qwen3 · Gemma 3</span>')
slides.append('<div class="local-copy"><h2 data-enter>로컬 LLM</h2><span data-enter>내 컴퓨터</span></div>'+art('local-llm','large-object','left:760px;top:55px;width:1090px;height:1090px;','내 컴퓨터에서 실행되는 AI 모델'))
slides.append(f'<div class="hub-copy"><div data-enter>{logo("huggingface","Hugging Face")}</div><h2 data-enter>모델 모음집</h2></div>'+art('huggingface-models','hub-screen','left:855px;top:190px;width:1040px;height:725px;','Hugging Face 공식 공개 모델 목록'))
slides.append('<h2 class="scene-word" data-enter>학습데이터</h2>'+f'<div class="company-stack"><div class="company-google enter-brand"><img src="assets/logos/google-company.png" alt="Google 공식 회사 로고"></div>{logo("anthropic-company","Anthropic","enter-brand")}{logo("openai-company","OpenAI","enter-brand company-openai")}</div>'+art('local-llm','learning-computer','left:1175px;top:300px;width:600px;height:600px;','고객의 로컬 모델')+'<span class="learning-question" data-enter>?</span>'+arrow('learning-arrow','left:830px;top:655px;width:230px;height:65px;',True)+'<span class="small-caption" style="left:1340px;top:920px" data-enter>내 컴퓨터</span>')
slides.append('<div class="center-copy"><h2 data-enter><span>회사</span><span>데이터센터</span></h2></div>'+art('datacenter','large-object','left:865px;top:75px;width:975px;height:975px;','회사 데이터센터에서 실행되는 AI 모델'))
slides.append(art('datacenter','web-company','left:100px;top:220px;width:650px;height:650px;','서버의 AI 모델')+art('web-chat','web-client','left:1115px;top:250px;width:740px;height:740px;','웹사이트의 챗봇 화면')+'<span class="request-label" data-enter>질문</span>'+arrow('request-arrow','left:795px;top:420px;width:300px;height:70px;',True)+'<span class="response-label" data-enter>대답</span>'+arrow('response-arrow','left:795px;top:665px;width:300px;height:70px;')+'<span class="web-caption" data-enter>웹사이트</span>')
slides.append(art('web-chat','large-object','left:105px;top:110px;width:990px;height:990px;','익숙한 웹 챗봇')+f'<div class="side-copy"><h2 data-enter>ChatBot</h2><div class="brand-stack">{logo("chatgpt","ChatGPT","enter-brand")}{logo("claude","Claude","enter-brand")}{logo("gemini","Gemini","enter-brand")}</div></div>')
slides.append('<div class="flyer-copy"><h2 data-enter>HTML</h2><span data-enter>전단지</span></div>'+art('html-flyer','large-object','left:880px;top:40px;width:1020px;height:1020px;','웹 화면을 전단지에 비유한 그림'))
slides.append('<h2 class="scene-word" data-enter>해줘</h2>'+art('html-flyer','limited-page','left:110px;top:260px;width:680px;height:680px;','실행 도구가 연결되기 전의 대화 화면')+'<div class="site-boundary" aria-hidden="true"></div>'+arrow('blocked-arrow','left:880px;top:550px;width:230px;height:70px;')+cross('cant-cross','left:970px;top:500px;width:150px;height:150px;')+sprite(4,'large-object','left:1190px;top:350px;width:590px;height:590px;')+'<span class="small-caption" style="left:260px;top:940px" data-enter>도구 연결 전</span>')
slides.append('<h2 class="site-label" style="left:175px" data-enter>내 사이트</h2><h2 class="site-label" style="left:1190px" data-enter>AI 사이트</h2>'+art('own-site','own-site-before','left:105px;top:285px;width:730px;height:730px;','내 웹사이트')+art('web-chat','external-site','left:1135px;top:285px;width:730px;height:730px;','다른 회사의 완성된 챗봇 웹사이트')+arrow('import-arrow','left:850px;top:515px;width:230px;height:70px;',True)+cross('site-cross','left:890px;top:475px;width:150px;height:150px;'))
slides.append('<h2 class="api-story-title" data-enter>API</h2>'+art('own-site','own-site-connected','left:95px;top:285px;width:700px;height:700px;','API 응답을 사용하는 내 웹사이트')+art('datacenter','api-server','left:1210px;top:300px;width:620px;height:620px;','API로 연결하는 AI 서버')+'<span class="api-request-label" data-enter>요청</span>'+arrow('api-request-arrow','left:805px;top:455px;width:300px;height:70px;')+'<span class="api-data-label" data-enter>데이터</span>'+arrow('api-data-arrow','left:805px;top:705px;width:300px;height:70px;',True)+'<span class="small-caption" style="left:340px;top:945px" data-enter>내 사이트</span><span class="small-caption" style="left:1400px;top:945px" data-enter>AI 서버</span>')
slides.append('<h2 class="scene-word app-question" data-enter>내 컴퓨터의 앱이라면?</h2>'+sprite(4,'large-object','left:100px;top:340px;width:650px;height:650px;')+art('datacenter','app-server','left:1230px;top:310px;width:600px;height:600px;','API 요청을 처리하는 원격 AI 모델','remote-model')+arrow('app-request-arrow','left:810px;top:515px;width:300px;height:70px;')+arrow('app-data-arrow','left:810px;top:715px;width:300px;height:70px;',True)+'<span class="app-api" data-enter>API</span><span class="small-caption" style="left:235px;top:945px" data-enter>내 컴퓨터</span><span class="small-caption" style="left:1370px;top:945px" data-enter>원격 AI</span>' )
slides.append('<h2 class="scene-word" data-enter>AI Agent</h2>'+art('datacenter','remote-brain','left:115px;top:365px;width:580px;height:580px;','외부 데이터센터에서 실행되는 AI 모델','remote-model')+arrow('agent-compute-arrow','left:760px;top:540px;width:280px;height:70px;')+sprite(4,'large-object','left:1150px;top:325px;width:580px;height:580px;')+art('agent-hand','local-agent-hand','left:1335px;top:585px;width:400px;height:400px;','내 컴퓨터에서 도구를 조작하는 에이전트','agent-hand')+'<span class="structure-caption" style="left:230px" data-enter>생각은 원격 AI</span><span class="structure-caption" style="left:1160px" data-enter>실행은 내 컴퓨터</span>' )
slides.append('<h2 class="scene-word" data-enter>연결해서, 실행</h2>'+sprite(4,'large-object','left:70px;top:365px;width:520px;height:520px;')+art('agent-hand','service-hand','left:360px;top:360px;width:650px;height:650px;','연결된 서비스를 조작하는 에이전트의 손','agent-hand')+arrow('services-arrow','left:940px;top:575px;width:190px;height:65px;')+'<div class="service-logos">'+logo('gmail','메일','enter-brand')+logo('slack','Slack','enter-brand service-slack')+logo('kakaotalk','카카오톡','enter-brand')+logo('github','GitHub','enter-brand')+'</div>' )
slides.append('<h2 class="scene-word" data-enter>내 컴퓨터에 설치</h2><div class="agent-lineup installed-agents"><div class="agent-mark" data-enter>'+logo('openclaw','OpenClaw')+'</div><div class="agent-mark" data-enter>'+logo('pi-agent','Pi')+'</div><div class="agent-mark" data-enter>'+logo('hermes-agent','Hermes')+'</div></div>'+sprite(4,'large-object','left:160px;top:670px;width:350px;height:350px;')+'<span class="installed-api" data-enter>AI API</span>'+arrow('installed-arrow','left:795px;top:815px;width:250px;height:65px;')+art('datacenter','installed-server','left:1170px;top:660px;width:365px;height:365px;','에이전트가 API로 빌리는 원격 AI 컴퓨팅','remote-model') )
slides.append('<div class="do-copy"><h2 data-enter>해줘</h2><span data-enter>이메일 보내줘</span><span data-enter>컴퓨터 고쳐줘</span></div>'+art('agent-hand','working-hand','left:900px;top:140px;width:850px;height:850px;','실제 작업을 실행하는 에이전트의 손')+sprite(5,'done-files','left:1420px;top:700px;width:360px;height:360px;'))
slides.append('<div class="always-copy"><h2 data-enter>24시간</h2><span data-enter>비서</span></div>'+art('agent-hand','large-object','left:905px;top:100px;width:930px;height:930px;','상시 실행 환경에서 요청과 일정을 처리하는 비서'))
slides.append(f'<div class="cli-copy"><h2 data-enter>CLI</h2><div class="cli-brands">{logo("gemini-cli","Gemini CLI","enter-brand")}{logo("claude","Claude Code","enter-brand")}{logo("codex-provider","Codex CLI","enter-brand")}</div></div>'+sprite(3,'large-object','left:950px;top:100px;width:870px;height:870px;'))
slides.append(f'<div class="gui-copy"><h2 data-enter>GUI</h2><div class="gui-brands">{logo("antigravity","Antigravity","enter-brand")}{logo("claude","Claude Desktop","enter-brand")}{logo("codex-provider","Codex","enter-brand")}</div></div>'+sprite(4,'large-object','left:930px;top:150px;width:890px;height:890px;'))
slides.append(sprite(0,'large-object compare-brain','left:840px;top:10px;width:240px;height:240px;')+'<span class="compare-common" data-enter>같은 구독, 원격 AI</span><svg class="compare-path" viewBox="0 0 1920 1080" aria-hidden="true"><path d="M850 160H480V310 M460 290L480 310L500 290 M1070 160H1435V310 M1415 290L1435 310L1455 290"/></svg><h2 class="compare-heading compare-chat" data-enter>ChatBot</h2><span class="compare-versus" data-enter>vs</span><h2 class="compare-heading compare-agent" data-enter>Agent</h2>'+art('web-chat','compare-web','left:145px;top:445px;width:680px;height:530px;','회사 서비스에 대화 기록을 남기는 챗봇')+sprite(4,'large-object compare-computer','left:1100px;top:445px;width:570px;height:570px;')+art('markdown-memory','compare-memory','left:1550px;top:680px;width:270px;height:270px;','내 컴퓨터에 남기는 Markdown 작업 기록','markdown-memory')+'<span class="compare-caption compare-company-record" data-enter>AI 회사에 기록</span><span class="compare-caption compare-local-record" data-enter>내 컴퓨터에 .md</span>')
slides.append('<div class="memory-copy"><h2 data-enter>내 컴퓨터에</h2><div class="memory-names"><span data-enter>작업.md</span><span data-enter>취향.md</span><span data-enter>일정.md</span></div></div>'+f'<div class="memory-agent enter-brand">{logo("claude","Claude Code")}</div>'+sprite(4,'large-object memory-computer','left:690px;top:695px;width:290px;height:290px;')+art('markdown-memory','memory-stack','left:1020px;top:120px;width:740px;height:840px;','작업과 선호, 일정 맥락을 저장한 Markdown 파일','markdown-memory'))
slides.append('<div class="handoff-copy"><h2 data-enter>마저해줘</h2><span data-enter>파일은 그대로</span></div>'+f'<div class="memory-agent handoff-agent enter-brand">{logo("codex-provider","Codex")}</div>'+sprite(4,'large-object memory-computer','left:690px;top:695px;width:290px;height:290px;')+art('markdown-memory','memory-stack','left:1020px;top:120px;width:740px;height:840px;','다른 에이전트가 같은 Markdown 파일을 읽고 이어가는 작업','markdown-memory'))
slides.append(art('markdown-memory','control-stack','left:120px;top:115px;width:800px;height:850px;','직접 읽고 편집하고 옮길 수 있는 내 작업 기록','markdown-memory')+'<h2 class="control-title" data-enter>내가 관리</h2>')
slides.append('<div class="personal-copy"><h2 data-enter>나에게 맞게</h2><span data-enter>취향 · 일정 · 업무</span></div>'+art('markdown-memory','personal-memory','left:310px;top:615px;width:330px;height:330px;','다음 작업에서 다시 읽는 나의 기록','markdown-memory')+art('personal-context','personal-organizer','left:850px;top:150px;width:990px;height:900px;','업무와 일정, 선호를 반영하는 개인 작업 환경'))
slides.append('<h2 class="scene-word" data-enter>내 방식대로</h2>'+art('markdown-memory','custom-memory','left:100px;top:375px;width:440px;height:530px;','내 선호와 업무 맥락이 쌓인 Markdown 파일','markdown-memory')+arrow('custom-input','left:565px;top:610px;width:200px;height:60px;')+art('agent-hand','custom-hand','left:770px;top:325px;width:590px;height:590px;','나의 기록을 읽고 작업하는 에이전트','agent-hand')+arrow('custom-output','left:1325px;top:610px;width:130px;height:60px;')+sprite(5,'large-object','left:1470px;top:455px;width:400px;height:400px;')+'<span class="small-caption" style="left:1540px;top:900px" data-enter>맞춤 결과</span>' )
slides.append('<div class="automation-copy"><span data-enter>해줘</span><h2 data-enter>자동화</h2></div>'+art('agent-hand','automation-hand','left:920px;top:105px;width:905px;height:905px;','연결된 도구로 디지털 업무를 실행하는 에이전트의 손')+'<span class="automation-scope" data-enter>디지털 업무</span>')
slides.append('<div class="schedule-copy concrete-schedule"><h2 data-enter>매일 09:00</h2><div class="schedule-sources">'+logo('gmail','메일')+logo('google-calendar','캘린더')+'</div><span data-enter>놓치면 안 되는<br>임박한 일정, 알려줘</span></div>'+art('automation-calendar','schedule-calendar','left:910px;top:150px;width:940px;height:850px;','메일과 구글 캘린더에서 중요한 임박 일정을 매일 아침 알려주는 자동화 예시') )
slides.append('<div class="job-intro"><span data-enter>예를 들어</span><h2 data-enter>취업준비</h2></div>'+art('own-site','job-site','left:1030px;top:90px;width:800px;height:710px;','새로운 채용 공고를 확인하는 취업 준비','job-posting')+'<div class="job-route" data-enter><span>공고 찾기</span><b>→</b><span>스펙 비교</span><b>→</b><span>서류 준비</span><b>→</b><span>확인 · 제출</span></div>' )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>01</span><h2 data-enter>새 공고 찾기</h2><p data-enter>아침마다</p></div>'+art('own-site','job-site','left:830px;top:240px;width:1000px;height:800px;','아침마다 새로 올라온 취업 공고를 찾는 웹사이트','job-posting')+art('agent-hand','job-hand','left:695px;top:620px;width:380px;height:380px;','공고 검색을 실행하는 에이전트','job-agent-hand') )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>02</span><h2 data-enter>내 스펙과 비교</h2><p data-enter>맞는 공고만</p></div>'+art('own-site','job-site-filter','left:160px;top:680px;width:360px;height:325px;','검색한 채용 공고','job-posting')+art('personal-context','job-fit','left:820px;top:205px;width:960px;height:850px;','보유 역량과 선호 조건에 맞는 공고를 고르는 기준','job-criteria')+art('agent-hand','job-hand','left:530px;top:650px;width:370px;height:370px;','내 기준으로 공고를 필터링하는 에이전트','job-agent-hand') )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>03</span><h2 data-enter>내 서류 찾기</h2><p data-enter>컴퓨터 안에서</p></div>'+sprite(4,'large-object','left:840px;top:315px;width:660px;height:660px;')+sprite(5,'large-object job-documents','left:1420px;top:575px;width:405px;height:405px;')+art('agent-hand','job-hand','left:675px;top:600px;width:430px;height:430px;','허용한 폴더에서 지원 서류를 찾아 정리하는 에이전트','job-agent-hand') )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>04</span><h2 data-enter>공고에 맞춰 작성</h2><p data-enter>지원서 · 자기소개서</p></div>'+art('own-site','job-site-writing','left:140px;top:650px;width:370px;height:340px;','작성에 반영할 채용 공고','job-posting')+art('agent-hand','job-hand','left:850px;top:230px;width:650px;height:650px;','경험과 공고를 근거로 지원 문서를 작성하는 에이전트','job-agent-hand')+sprite(5,'large-object job-documents','left:1400px;top:630px;width:430px;height:430px;') )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>05</span><h2 data-enter>내가 확인</h2><p class="job-ok" data-enter>OK</p></div>'+art('human-work','job-human-review','left:720px;top:260px;width:1000px;height:800px;','제출 전에 사실과 적합성을 확인하는 사람')+sprite(5,'large-object job-documents','left:1430px;top:610px;width:405px;height:405px;') )
slides.append('<div class="job-copy"><span class="job-kicker" data-enter>06</span><h2 data-enter>제출까지</h2><p data-enter>OK 하면</p></div>'+art('agent-hand','job-hand','left:660px;top:450px;width:525px;height:525px;','사람이 승인한 지원서를 제출하는 에이전트','job-agent-hand')+sprite(5,'large-object job-documents','left:990px;top:420px;width:400px;height:400px;')+arrow('submit-arrow','left:1330px;top:710px;width:170px;height:60px;')+art('own-site','job-site-submit','left:1470px;top:515px;width:380px;height:360px;','지원서를 접수하는 채용 사이트','job-posting') )
slides.append('<div class="rules-copy"><h2 data-enter>검토 기준을</h2><strong data-enter>규칙.md</strong><span data-enter>다음에도 기억하게</span></div>'+art('markdown-memory','rules-memory','left:965px;top:205px;width:775px;height:825px;','검토하며 정한 반복 가능한 기준을 기록한 Markdown 파일','markdown-memory')+sprite(5,'large-object job-documents','left:690px;top:655px;width:320px;height:320px;') )
slides.append('<h2 class="scene-word" data-enter>다음에는, 규칙대로 검토</h2>'+art('markdown-memory','next-rules','left:95px;top:390px;width:460px;height:530px;','다음 실행에서 읽는 나의 검토 규칙','markdown-memory')+arrow('next-rules-arrow','left:590px;top:610px;width:180px;height:60px;')+art('agent-hand','rules-hand','left:745px;top:325px;width:610px;height:610px;','명시된 기준의 검토를 대신 수행하는 에이전트','job-agent-hand')+arrow('reviewed-arrow','left:1360px;top:610px;width:125px;height:60px;')+sprite(5,'large-object job-documents','left:1490px;top:450px;width:390px;height:390px;')+'<span class="small-caption" style="left:180px;top:945px" data-enter>규칙.md</span><span class="small-caption" style="left:1450px;top:915px" data-enter>예외는 내게</span>' )
slides.append('<h2 class="scene-word" data-enter>각자의 PC</h2>'+''.join(sprite(4,'large-object',f'left:{x}px;top:330px;width:500px;height:500px;')+art('markdown-memory','scattered-file',f'left:{x+300}px;top:710px;width:225px;height:225px;','각 개인 컴퓨터에 흩어진 작업 기록',f'local-record-{i}') for i,x in enumerate([80,710,1340])))
slides.append('<div class="ax-copy ax-definition"><h2 data-enter>AX</h2><span data-enter>사람 중심의 일에서<br>Agent 중심의 일로</span></div>'+art('ax-workspace','ax-workspace','left:820px;top:145px;width:1030px;height:925px;','파편화된 자료와 실행을 중앙에서 관리하는 에이전트 중심 업무 구조') )
slides.append('<span class="ax-step" data-enter>01</span><h2 class="ax-step-title" data-enter>디지털화 · 중앙화</h2>'+sprite(4,'large-object central-left','left:85px;top:445px;width:500px;height:500px;')+sprite(4,'large-object central-right','left:1310px;top:445px;width:500px;height:500px;')+arrow('central-arrow-left','left:600px;top:650px;width:220px;height:60px;')+arrow('central-arrow-right','left:1120px;top:650px;width:220px;height:60px;',True)+art('markdown-memory','central-record','left:760px;top:355px;width:400px;height:550px;','흩어진 자료를 디지털화하고 권한을 정해 중앙에서 관리하는 업무 자산','local-record-1')+'<span class="small-caption" style="left:825px;top:955px" data-enter>공용 자산</span>' )
slides.append('<span class="ax-step" data-enter>02</span><h2 class="ax-step-title" data-enter>Agent가 할 수 있는 흐름</h2>'+art('markdown-memory','workflow-record','left:90px;top:400px;width:400px;height:500px;','에이전트가 읽을 수 있는 중앙의 업무 자료와 기준','local-record-1')+arrow('workflow-input','left:520px;top:625px;width:220px;height:60px;')+art('agent-hand','workflow-hand','left:735px;top:340px;width:600px;height:600px;','자료를 읽고 도구를 실행하고 결과를 검토하는 공용 에이전트','agent-hand')+arrow('workflow-output','left:1350px;top:625px;width:120px;height:60px;')+sprite(5,'large-object','left:1490px;top:475px;width:370px;height:370px;')+'<span class="workflow-label" style="left:215px" data-enter>자료 · 기준</span><span class="workflow-label" style="left:900px" data-enter>실행 · 검토</span><span class="workflow-label" style="left:1550px" data-enter>결과</span>' )
slides.append('<h2 class="scene-word" data-enter>공용 에이전트</h2>'+art('markdown-memory','shared-record','left:125px;top:405px;width:330px;height:430px;','중앙에서 관리하는 업무 지침과 기록','local-record-1')+arrow('shared-record-arrow','left:480px;top:550px;width:240px;height:65px;')+art('agent-hand','shared-agent-hand','left:770px;top:275px;width:640px;height:640px;','중앙에서 운영하고 배정하는 에이전트')+''.join(sprite(4,'large-object assigned-computer',f'left:1540px;top:{y}px;width:250px;height:250px;') for y in [250,510,770])+'<span class="shared-caption" data-enter>중앙에서 배정</span>')
slides.append('<span class="ax-step" data-enter>03</span><div class="vibe-copy ax-vibe"><span data-enter>막히는 곳은</span><h2 data-enter>바이브코딩</h2><p data-enter>필요한 툴을 만들고</p></div>'+sprite(3,'large-object','left:970px;top:185px;width:830px;height:830px;') )
slides.append('<span class="ax-step" data-enter>04</span><h2 class="ax-step-title" data-enter>고객도 Agent</h2>'+art('own-site','customer-site','left:110px;top:370px;width:700px;height:630px;','고객의 에이전트가 이용할 수 있는 우리 서비스')+arrow('customer-arrow','left:860px;top:620px;width:240px;height:65px;',True)+art('agent-hand','customer-hand','left:1190px;top:340px;width:630px;height:630px;','고객을 대신해 서비스에 접근하는 에이전트','agent-hand') )
slides.append('<div class="interface-copy"><h2 data-enter>CLI · API · MCP</h2></div>'+art('own-site','accessible-site','left:120px;top:370px;width:650px;height:620px;','프로그램과 에이전트가 연결할 수 있게 만든 우리 서비스')+sprite(2,'large-object interface-plug','left:940px;top:225px;width:900px;height:900px;'))
slides.append('<div class="human-work-copy"><h2 data-enter>사람은<br>사람 일에</h2><span data-enter>시간 · 비용</span></div>'+art('human-work','human-work','left:830px;top:130px;width:1060px;height:920px;','대화와 판단에 집중하는 사람들의 협업'))
slides.append('<div class="rental-copy"><h2 data-enter>모델은<br>빌려서</h2><div class="rental-brands">'+logo('chatgpt','','enter-brand')+logo('claude','','enter-brand')+logo('gemini','','enter-brand')+'</div></div>'+sprite(0,'large-object','left:970px;top:100px;width:850px;height:850px;'))
ids=['opening', 'makers', 'models', 'download', 'local', 'hub', 'learning', 'datacenter', 'web', 'chat', 'flyer', 'cant_do', 'my_site', 'api', 'local_app', 'agent_structure', 'services', 'agents', 'do_it', 'always_on', 'cli', 'gui', 'compare', 'local_files', 'handoff', 'control', 'personal', 'custom_result', 'automation', 'schedule', 'job_start', 'job_find', 'job_filter', 'job_documents', 'job_write', 'job_review', 'job_submit', 'rules', 'rules_run', 'scattered', 'ax', 'centralize', 'agent_workflow', 'shared_agents', 'vibe_tools', 'agent_customers', 'interfaces', 'human_work', 'rented_model']
motion_modes={'compare':'compare','local_files':'accumulate','handoff':'handoff','control':'handoff','personal':'accumulate','scattered':'compare','centralize':'accumulate','shared_agents':'accumulate','ax':'accumulate','agent_workflow':'accumulate','custom_result':'accumulate','rules':'accumulate','rules_run':'handoff'}
manifest=json.loads((p/'manifest.json').read_text())
assert [s['sceneId'] for s in manifest['slides']]==ids
css=(p/'composition/deck.css').read_text()
head='<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChatBot에서 Agent로</title><script src="vendor/gsap.min.js"></script><style>'+css+'</style></head><body>\n'
head+='<script type="application/hyperframes-slideshow+json">'+json.dumps(manifest,ensure_ascii=False)+'</script>\n'
head+=f'<div data-composition-id="root" data-start="0" data-duration="{len(slides)*6}" data-width="1920" data-height="1080" data-label="Navigation clock" aria-hidden="true" style="position:absolute;width:1920px;height:1080px;pointer-events:none"></div>'
for i,content in enumerate(slides):
 head+=f'<div id="scene-{ids[i]}" class="scene-frame clip" data-composition-id="{ids[i]}" data-start="{i*6}" data-duration="6" data-track-index="{i+1}" data-width="1920" data-height="1080" data-label="{ids[i]}" data-motion="{motion_modes.get(ids[i],"handoff")}"><div class="slide-motion">{content}</div></div>\n'
head+='<script>window.__timelines=window.__timelines||{};window.__timelines["root"]=gsap.timeline({paused:true});'+(p/'composition/deck-runtime.js').read_text()+'</script></body></html>'
(p/'composition/index.html').write_text(head)
